### ISSUE TITLE
能否开源

### ISSUE THREAD

**Issue by ghost** [JuniperPhoton/Photon-AI-Translator-Support#1]
您好,JuniperPhoton,可能我这样样说有些冒昧。

就我想着既然Photon AI Translator不盈利,你也放出了相应的一些api,我想着就能不能将Photon AI Translator开源。

我觉得Translator的想法特别好,但是也有我不满意的地方,也有一些自己想法,

可是这些不满意的地方和想法只是对于我来说,可能只符合我自己的使用习惯,

可是自己也写个Translator却无从下手,

网上关于菜单栏软件的教程少,也很少像你这样处理得那么好的菜单栏软件。

**Comment by JuniperPhoton** [comment]
感谢你的反馈和支持。

在之前，我的所有 apps 都是开源的， 包括 Android 和 Windows 平台的，但也有人直接使用代码通过简单改图标和名字（甚至反馈邮件都不改）的方式来上架到 Store 并直接收费，因此在那之后就把我的 apps 都闭源了。这是最直接的原因。

在后续我基本只会对自己写的库做开源，这样能方便其他开发者使用也没有任何其他问题。

关于 app 本身，如果你有什么不满意的地方，欢迎提出，能满足我会尽量满足一下。

至于最后关于 Menu Bar only 的 app，我确实在此 app 内下了点功夫来打磨了下，将来有时间也会打算写一系列文章来说说（可以从[这里顶部进入博客](https://juniperphoton.dev/photonapps/)）。

当然关于 Menu Bar 本身，我可以先暂时提供一些思路：
- 如果你仅限满足 macOS 13 本身做支持，那么使用 SwiftUI 的 [MenuBarExtra](https://developer.apple.com/documentation/swiftui/menubarextra/) 就好了，但是无法通过代码的方式显示它对应的 NSWindow，这个 NSWindow 是被 SwiftUI 创建管理的
- 在后来为了支持 macOS 12，我便自己从 NSAppDelegate 开始自己管理 NSWindow，你所见的 Menu Bar 样式、Spotlight 央视以及新版马上就有的截屏翻译模式，里面的 UI 都是在一个个的 NSWindow 里，无非就是设置的一些 Style 不一样；然后想办法把 SwiftUI View 嵌进去显示，仅此而已

**Comment by JuniperPhoton** [comment]
我最新的 Blog 已经展示了如何实现一个支持 macOS 12 或以下的 Menu Bar only macOS app 了：

https://juniperphoton.dev/swiftui-menu-bar/

希望能帮到你。
