### ISSUE TITLE
Request for Consistency in Dark Mode History Panel in Photon AI Translator

### ISSUE THREAD

**Issue by singularitti** [JuniperPhoton/Photon-AI-Translator-Support#2]
Dear Photon AI Translator Developer,

I've been a long-time user of the Photon AI Translator app for macOS, and I wanted to provide some feedback regarding the recent changes to the History Panel.

In the current dark mode, the History Panel displays in two colors: gray and dark, while in light mode, it's consistent with a single white color. This color separation and inconsistency doesn't align with the prior design, where the dark mode panel was consistently black.

![dark](https://github.com/JuniperPhoton/Photon-AI-Translator-Support/assets/25192197/45df10f1-beee-4a01-9479-e360151fdd7e)

![white](https://github.com/JuniperPhoton/Photon-AI-Translator-Support/assets/25192197/ec282a4a-15ff-4163-abb7-004166c294bd)

I'd like to express my preference for the previous, consistently black History Panel in dark mode:

![hist](https://github.com/JuniperPhoton/Photon-AI-Translator-Support/assets/25192197/64a34a59-ea2c-4d79-82c7-03aed9678751)

And I hope this recent change can be considered a bug that will be resolved in a future update.

Thank you for your dedication to improving Photon AI Translator, and I look forward to the possibility of seeing this issue addressed in an upcoming update.

**Comment by JuniperPhoton** [comment]
Thanks for your feedback.

The consistent issue may be due to the change of using a material background in Dark mode (I opt out of this in light mode). However, I may consider removing the material background in the next version due to the reading accessibility issues it may introduce and use near black instead.

**Comment by singularitti** [comment]
Sounds great! Thanks!

**Comment by JuniperPhoton** [comment]
This new v2.5.5 is released for all platforms.

**Comment by singularitti** [comment]
Thank you!
